[versions]
agp = "8.4.2"
kotlin = "1.9.0"
coroutines = "1.8.1"
androidx-activity = "1.9.2"
androidx-recyclerview = "1.3.2"

# Sdk versions
minSdk = "24"
compileSdk = "34"
targetSdk = "34"

[libraries]
androidx-activity = { group = "androidx.activity", name = "activity-ktx", version.ref = "androidx-activity" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "androidx-recyclerview" }
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }

[plugins]
android =  { id = "com.android.application", version.ref = "agp" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
